version: '3.4'

services:
    linktms.apigateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTPS_PORT=7256
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_Kestrel__Certificates__Default__Password=johnbuen
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/linkdispatch.webapi.pfx
        ports:
            - 5125:80
            - 7125:443
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro