version: '3.4'

services:
  linktms.apigateway:
    image: registry.loadlink.ca/linktmsapigateway:v1
    ports:
        - 5125:80
        - 7125:443
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTPS_PORT=7125
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_Kestrel__Certificates__Default__Password=johnbuen
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/linkdispatch.webapi.pfx
    volumes:
        - ${USERPROFILE}/.aspnet/https:/https/ 
    build:
      context: .
      dockerfile: LinkTMS.ApiGateway/Dockerfile